/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;
import entidades.Bodegas;
import datos.Dt_bodegas;



import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
        

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;
/**
 *
 * @author cchav
 */
public class FrmBodegas extends javax.swing.JFrame {

    private Bodegas bodegas = new Bodegas();
    private Dt_bodegas dt_bodegas = new Dt_bodegas();
    private ArrayList<Bodegas> listBodegas = new ArrayList<Bodegas>();
    
    DefaultTableModel myData = new DefaultTableModel();
    TableRowSorter trsfiltro;
    
    /**
     * Creates new form FrmBodegas
     */
    public FrmBodegas() {
        initComponents();
        llenarTablaBodegas();
        limpiarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tf_bodegaID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_tiendaID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_noDocumento = new javax.swing.JTextArea();
        btn_editar = new javax.swing.JButton();
        btn_vaciar_campos = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tf_buscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_bodegas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(815, 571));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(815, 571));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tf_bodegaID.setBackground(new java.awt.Color(204, 204, 204));
        tf_bodegaID.setForeground(new java.awt.Color(0, 0, 0));
        tf_bodegaID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_bodegaIDActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("BodegaID:");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("TiendaID:");

        tf_tiendaID.setBackground(new java.awt.Color(204, 204, 204));
        tf_tiendaID.setForeground(new java.awt.Color(0, 0, 0));
        tf_tiendaID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_tiendaIDActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre:");

        tf_nombre.setBackground(new java.awt.Color(204, 204, 204));
        tf_nombre.setForeground(new java.awt.Color(0, 0, 0));
        tf_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nombreActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("No. documento: ");

        ta_noDocumento.setBackground(new java.awt.Color(204, 204, 204));
        ta_noDocumento.setColumns(20);
        ta_noDocumento.setForeground(new java.awt.Color(0, 0, 0));
        ta_noDocumento.setRows(5);
        jScrollPane2.setViewportView(ta_noDocumento);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_bodegaID, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_tiendaID, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tf_bodegaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tf_tiendaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 790, 120));

        btn_editar.setBackground(new java.awt.Color(153, 153, 153));
        btn_editar.setForeground(new java.awt.Color(0, 0, 0));
        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        btn_vaciar_campos.setBackground(new java.awt.Color(153, 153, 153));
        btn_vaciar_campos.setForeground(new java.awt.Color(0, 0, 0));
        btn_vaciar_campos.setText("Vaciar campos");
        btn_vaciar_campos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vaciar_camposActionPerformed(evt);
            }
        });
        jPanel1.add(btn_vaciar_campos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        btn_eliminar.setBackground(new java.awt.Color(153, 153, 153));
        btn_eliminar.setForeground(new java.awt.Color(0, 0, 0));
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        btn_guardar.setBackground(new java.awt.Color(153, 153, 153));
        btn_guardar.setForeground(new java.awt.Color(0, 0, 0));
        btn_guardar.setText("Guardar");
        btn_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_guardarMouseClicked(evt);
            }
        });
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Buscar:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        tf_buscar.setBackground(new java.awt.Color(204, 204, 204));
        tf_buscar.setForeground(new java.awt.Color(0, 0, 0));
        tf_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_buscarKeyTyped(evt);
            }
        });
        jPanel1.add(tf_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 370, -1));

        tbl_bodegas.setBackground(new java.awt.Color(204, 204, 204));
        tbl_bodegas.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        tbl_bodegas.setForeground(new java.awt.Color(0, 0, 0));
        tbl_bodegas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "BodegaID", "TiendaID", "Nombre", "No de documento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_bodegas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_bodegasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_bodegas);
        if (tbl_bodegas.getColumnModel().getColumnCount() > 0) {
            tbl_bodegas.getColumnModel().getColumn(1).setResizable(false);
            tbl_bodegas.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 800, 310));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_bodegaIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_bodegaIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_bodegaIDActionPerformed

    private void tf_tiendaIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_tiendaIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_tiendaIDActionPerformed

    private void tf_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nombreActionPerformed

    private void btn_vaciar_camposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vaciar_camposActionPerformed
        limpiarCampos();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_vaciar_camposActionPerformed

    private void btn_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_guardarMouseClicked

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        if(tf_nombre.getText().equals("") || ta_noDocumento.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Todos los campos son requeridos!", 
                    "ERROR", JOptionPane.WARNING_MESSAGE);
        }
        else{
            bodegas.setTiendaID(1);
            bodegas.setNombre(tf_nombre.getText());
            bodegas.setNo_documento(ta_noDocumento.getText());
            
            
            
//            VAlIDACION DE NOMBRES NO IGUALES
//            if(dtc.existePais(c.getCountry_id())){
//                JOptionPane.showMessageDialog(this, "El Id de pais ya existe!", 
//                    "ERROR", JOptionPane.WARNING_MESSAGE);
//                jtf_id.setText("");
//                jtf_id.grabFocus(); 
//            }

            if(dt_bodegas.guardarBodegas(bodegas)){
                JOptionPane.showMessageDialog (this, "El registro fue almacenado con éxito!", 
                      "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
                    actualizarTabla();
                    limpiarCampos();
            } 
            else{
                   JOptionPane.showMessageDialog(this, 
                      "Revise los datos e intente nuevamente. Si el error persiste contacte al Administrador del Sistema.", 
                      "ERROR", JOptionPane.ERROR_MESSAGE); 
                }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void tf_buscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_buscarKeyTyped
        
        // TODO add your handling code here:
        
        tf_buscar.addKeyListener(new KeyAdapter() {
            
            @Override
            public void keyReleased(final KeyEvent e){
               String cadena = (tf_buscar.getText()).toUpperCase();
               tf_buscar.setText(cadena);
               repaint();
               filtrarTabla();
                
                
            }
        
        });
        trsfiltro = new TableRowSorter(tbl_bodegas.getModel());
        tbl_bodegas.setRowSorter(trsfiltro);
    }//GEN-LAST:event_tf_buscarKeyTyped

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        // TODO add your handling code here:
        if(tf_bodegaID.getText().equals("") || tf_tiendaID.getText().equals("") || tf_nombre.getText().equals("") || ta_noDocumento.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Todos los campos son requeridos!", 
                    "ERROR", JOptionPane.WARNING_MESSAGE);
        }
        else{
            bodegas.setBodegaID(Integer.parseInt(tf_bodegaID.getText()));
            bodegas.setTiendaID(Integer.parseInt(tf_bodegaID.getText()));
            bodegas.setNombre(tf_nombre.getText());
            bodegas.setNo_documento(ta_noDocumento.getText());
            
            
            if(dt_bodegas.editarBodega(bodegas)){
                JOptionPane.showMessageDialog (this, "El registro fue actualizado con éxito!", 
                  "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
                actualizarTabla();
                limpiarCampos();
            }
            else{
                JOptionPane.showMessageDialog(this, 
                  "Revise los datos e intente nuevamente. Si el error persiste contacte al Administrador del Sistema.", 
                  "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_btn_editarActionPerformed

    private void tbl_bodegasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_bodegasMouseClicked
        // TODO add your handling code here:
        int fila = tbl_bodegas.getSelectedRow();

        tf_bodegaID.setText(tbl_bodegas.getValueAt(fila, 0).toString());
        tf_nombre.setText(tbl_bodegas.getValueAt(fila, 2).toString());
        tf_tiendaID.setText(tbl_bodegas.getValueAt(fila, 1).toString());
        ta_noDocumento.setText(tbl_bodegas.getValueAt(fila, 3).toString());
        
    }//GEN-LAST:event_tbl_bodegasMouseClicked

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // TODO add your handling code here:
                if(tf_bodegaID.getText().equals("") || tf_tiendaID.getText().equals("") || tf_nombre.getText().equals("") || ta_noDocumento.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Todos los campos son requeridos!", 
                    "ERROR", JOptionPane.WARNING_MESSAGE);
        }
        else{
            bodegas.setBodegaID(Integer.parseInt(tf_bodegaID.getText()));
            bodegas.setTiendaID(Integer.parseInt(tf_bodegaID.getText()));
            bodegas.setNombre(tf_nombre.getText());
            bodegas.setNo_documento(ta_noDocumento.getText());
            
            if(dt_bodegas.borrarBodega(bodegas.getBodegaID())){
                 JOptionPane.showMessageDialog (this, "El registro fue eliminado con éxito!", 
                  "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
                actualizarTabla();
                limpiarCampos();
            }
            else{
               JOptionPane.showMessageDialog(this, 
                  "Revise los datos e intente nuevamente. Si el error persiste contacte al Administrador del Sistema.", 
                  "ERROR", JOptionPane.ERROR_MESSAGE); 
            }
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void actualizarTabla(){
        myData.setColumnCount(0);
        myData.setRowCount(0);
        this.llenarTablaBodegas();
    }
    
    
    private void llenarTablaBodegas()
    {
         //llenamos la lista
        listBodegas = dt_bodegas.listarBodegas();
        
        //creamos un arraylist con las columnas del modelo
        ArrayList<Object> listNombreColumnas = new ArrayList<Object>();
        listNombreColumnas.add("BodegaID");
        listNombreColumnas.add("TiendaID");
        listNombreColumnas.add("Nombre");
        listNombreColumnas.add("No_documento");
        
        
        //recorremos cada elemento del arraylist y creamos un objeto
        for(Object column : listNombreColumnas){
            //asignamos las columnas al modelo
            myData.addColumn(column);
        }
        
       //recorremos cada elemento de la lista y creamos el objeto
        for(Bodegas bodegas: listBodegas){
            Object[] datosBod = new Object[]{bodegas.getBodegaID(), bodegas.getTiendaID(), bodegas.getNombre(), bodegas.getNo_documento()};
            //asignamos un arreglo de objetos a una fila del modelo
            myData.addRow(datosBod);
        }
        //Asignamos el modelo y/o coleccion de datos a la tabla
        tbl_bodegas.setModel(myData);
    }
    
        private void limpiarCampos(){
        this.tf_bodegaID.setText("");
        this.tf_tiendaID.setText("");
        this.tf_nombre.setText("");
        this.ta_noDocumento.setText("");
        
       
    }
        
    private void filtrarTabla(){
       trsfiltro.setRowFilter(RowFilter.regexFilter(tf_buscar.getText(), 2));
    }
        
    public JPanel getFondo(){
        return jPanel1;
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBodegas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBodegas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBodegas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBodegas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBodegas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_vaciar_campos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea ta_noDocumento;
    private javax.swing.JTable tbl_bodegas;
    private javax.swing.JTextField tf_bodegaID;
    private javax.swing.JTextField tf_buscar;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_tiendaID;
    // End of variables declaration//GEN-END:variables
}
