/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;



//Datos
import datos.Dt_inventarios;
import datos.Dt_Productos;
import datos.Dt_bodegas;

//Entidades
import entidades.Productos;
import entidades.Inventarios;
import entidades.Bodegas;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

//Librerias de java
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Francisco de Jesus Melendez Simplina
 */
public class FrmInventarios extends javax.swing.JFrame {
    
    Bodegas b = new Bodegas();
    Inventarios inv = new Inventarios();
    Productos pro = new Productos();

    private Dt_inventarios dt_inventario = new Dt_inventarios();
    private Dt_bodegas dt_bodega = new Dt_bodegas();
    private Dt_Productos dt_producto = new Dt_Productos();

    
    private ArrayList<Bodegas> listBodega = new ArrayList<Bodegas>();
    private ArrayList<Inventarios> listInventario = new ArrayList<Inventarios>();
    private ArrayList<Productos> listProductos = new ArrayList<Productos>();
    
    
    DefaultTableModel myData = new DefaultTableModel();
    TableRowSorter trsfiltro;

    /**
     * Creates new form FrmInventario
     */
    public FrmInventarios() {
        initComponents();
        llenarTablaProductos();
        llenarComboBodega();
        llenarComboProducto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtInventario = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_inventario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jf_ventas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jf_Fecha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jf_compras = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jf_cantInicial = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jf_saldoTotal = new javax.swing.JTextField();
        jcb_BodegaID = new javax.swing.JComboBox<>();
        jcb_Producto = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jtBuscar = new javax.swing.JTextField();
        jb_Guardar = new javax.swing.JButton();
        jb_Editar = new javax.swing.JButton();
        jb_Eliminar = new javax.swing.JButton();
        jb_Agregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inventario");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jtInventario.setBackground(new java.awt.Color(204, 204, 204));
        jtInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Inventario ID", "Bodega ID", "Producto ID", "Cantidad inicial", "Movimientos positivos", "Movimientos negativos", "Sueldo final", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jtInventario.setName(""); // NOI18N
        jtInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtInventarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtInventario);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Bodega ID:");

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Fecha:");

        tf_inventario.setEditable(false);
        tf_inventario.setBackground(new java.awt.Color(204, 204, 204));
        tf_inventario.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        tf_inventario.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Movimientos negativos:");

        jf_ventas.setBackground(new java.awt.Color(204, 204, 204));
        jf_ventas.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jf_ventas.setForeground(new java.awt.Color(0, 0, 0));
        jf_ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jf_ventasActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Inventarios");

        jf_Fecha.setBackground(new java.awt.Color(204, 204, 204));
        jf_Fecha.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jf_Fecha.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Movimientos positivos:");

        jf_compras.setBackground(new java.awt.Color(204, 204, 204));
        jf_compras.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jf_compras.setForeground(new java.awt.Color(0, 0, 0));
        jf_compras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jf_comprasActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Saldo Total:");

        jf_cantInicial.setEditable(false);
        jf_cantInicial.setBackground(new java.awt.Color(204, 204, 204));
        jf_cantInicial.setForeground(new java.awt.Color(0, 0, 0));
        jf_cantInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jf_cantInicialActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Cantidad inicial:");

        jf_saldoTotal.setBackground(new java.awt.Color(204, 204, 204));
        jf_saldoTotal.setForeground(new java.awt.Color(0, 0, 0));
        jf_saldoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jf_saldoTotalActionPerformed(evt);
            }
        });

        jcb_BodegaID.setBackground(new java.awt.Color(204, 204, 204));
        jcb_BodegaID.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jcb_BodegaID.setForeground(new java.awt.Color(0, 0, 0));
        jcb_BodegaID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione..." }));
        jcb_BodegaID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcb_BodegaIDMouseClicked(evt);
            }
        });
        jcb_BodegaID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_BodegaIDActionPerformed(evt);
            }
        });

        jcb_Producto.setBackground(new java.awt.Color(204, 204, 204));
        jcb_Producto.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jcb_Producto.setForeground(new java.awt.Color(0, 0, 0));
        jcb_Producto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione..." }));
        jcb_Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_ProductoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Producto ID:");

        jLabel8.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Inventario ID:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_inventario)
                                .addComponent(jcb_BodegaID, 0, 177, Short.MAX_VALUE))
                            .addComponent(jcb_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jf_Fecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jf_saldoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jf_ventas, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jf_compras, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jf_cantInicial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel8)
                    .addContainerGap(758, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_inventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jf_compras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_BodegaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jf_ventas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6)
                    .addComponent(jf_saldoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jf_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jf_cantInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(51, 51, 51)
                    .addComponent(jLabel8)
                    .addContainerGap(99, Short.MAX_VALUE)))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtBuscar.setBackground(new java.awt.Color(204, 204, 204));
        jtBuscar.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jtBuscar.setForeground(new java.awt.Color(0, 0, 0));
        jtBuscar.setText("Buscar...");
        jtBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtBuscarMouseClicked(evt);
            }
        });
        jtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtBuscarActionPerformed(evt);
            }
        });
        jtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtBuscarKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jb_Guardar.setBackground(new java.awt.Color(153, 153, 153));
        jb_Guardar.setForeground(new java.awt.Color(0, 0, 0));
        jb_Guardar.setText("Vaciar campos");
        jb_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_GuardarActionPerformed(evt);
            }
        });

        jb_Editar.setBackground(new java.awt.Color(153, 153, 153));
        jb_Editar.setForeground(new java.awt.Color(0, 0, 0));
        jb_Editar.setText("Editar");
        jb_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_EditarActionPerformed(evt);
            }
        });

        jb_Eliminar.setBackground(new java.awt.Color(153, 153, 153));
        jb_Eliminar.setForeground(new java.awt.Color(0, 0, 0));
        jb_Eliminar.setText("Eliminar");
        jb_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_EliminarActionPerformed(evt);
            }
        });

        jb_Agregar.setBackground(new java.awt.Color(153, 153, 153));
        jb_Agregar.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jb_Agregar.setForeground(new java.awt.Color(0, 0, 0));
        jb_Agregar.setText("Guardar");
        jb_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_AgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jb_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jb_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_Guardar)
                            .addComponent(jb_Eliminar)
                            .addComponent(jb_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jf_ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jf_ventasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jf_ventasActionPerformed

    private void jf_comprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jf_comprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jf_comprasActionPerformed

    private void jf_cantInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jf_cantInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jf_cantInicialActionPerformed

    private void jf_saldoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jf_saldoTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jf_saldoTotalActionPerformed

    private void jb_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_GuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_GuardarActionPerformed

    private void jb_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_EliminarActionPerformed
        // TODO add your handling code here:
        
        
        //**********************************Comprueba si todas las casillas estan llenas***********************************//
        if(jf_Fecha.getText().equals("") || jf_ventas.getText().equals("") || jcb_BodegaID.getSelectedIndex()==0||jcb_Producto.getSelectedIndex()==0||jf_compras.getText().equals("") || jf_cantInicial.getText().equals("")||jf_saldoTotal.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Todos los campos son requeridos!", 
                    "ERROR", JOptionPane.WARNING_MESSAGE);
        }
        else{
            //construimos nuestro objeto con los valores del formulario
            inv.setInventarioID(Integer.parseInt(tf_inventario.getText()));
            inv.setFecha(jf_Fecha.getText());
            inv.setMovimiento_neg(Integer.parseInt(jf_ventas.getText()));
            inv.setMovimiento_pos(Integer.parseInt(jf_compras.getText()));
            inv.setSaldo_final(Integer.parseInt(jf_saldoTotal.getText()));
            inv.setCant_inicial(Integer.parseInt(jf_cantInicial.getText()));
            
            pro = (Productos)this.jcb_Producto.getSelectedItem();
            inv.setProductoID(pro.getProducto_id());
            b = (Bodegas)this.jcb_BodegaID.getSelectedItem();
            inv.setBodegaID(b.getBodegaID());
            

            //validamos que el metodo delete devuelve un true
            if(dt_inventario.eliminarInventario(inv.getInventarioID())){
                
                
                JOptionPane.showMessageDialog (this, "El Usuario fue editado con éxito!", 
                  "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
                actualizarTabla();
                limpiarCampos();
            }
            else{
               JOptionPane.showMessageDialog(this, 
                  "Revise los datos e intente nuevamente. Si el error persiste contacte al Administrador del Sistema.", 
                  "ERROR", JOptionPane.ERROR_MESSAGE); 
            }
        }   
    }//GEN-LAST:event_jb_EliminarActionPerformed

    private void jb_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_EditarActionPerformed
        // TODO add your handling code here:
        
        //**********************************Comprueba si todas las casillas estan llenas***********************************//
        if(jf_Fecha.getText().equals("") || jf_ventas.getText().equals("") || jcb_BodegaID.getSelectedIndex()==0|| jcb_Producto.getSelectedIndex()==0||jf_compras.getText().equals("") || jf_cantInicial.getText().equals("")||jf_saldoTotal.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Todos los campos son requeridos!", 
                    "ERROR", JOptionPane.WARNING_MESSAGE);
        }
        else{
            //construimos nuestro objeto con los valores del formulario
            inv.setInventarioID(Integer.parseInt(tf_inventario.getText()));
            inv.setFecha(jf_Fecha.getText());
            inv.setMovimiento_neg(Integer.parseInt(jf_ventas.getText()));
            inv.setMovimiento_pos(Integer.parseInt(jf_compras.getText()));
            inv.setSaldo_final(Integer.parseInt(jf_saldoTotal.getText()));
            inv.setCant_inicial(Integer.parseInt(jf_cantInicial.getText()));
            
            pro = (Productos)this.jcb_Producto.getSelectedItem();
            inv.setProductoID(pro.getProducto_id());
            b = (Bodegas)this.jcb_BodegaID.getSelectedItem();
            inv.setBodegaID(b.getBodegaID());
            
            
            //validamos que el metodo delete devuelve un true
            if(dt_inventario.editarInventario(inv)){
                JOptionPane.showMessageDialog (this, "El Usuario fue editado con éxito!", 
                  "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
                actualizarTabla();
                limpiarCampos();
            }
            else{
               JOptionPane.showMessageDialog(this, 
                  "Revise los datos e intente nuevamente. Si el error persiste contacte al Administrador del Sistema.", 
                  "ERROR", JOptionPane.ERROR_MESSAGE); 
            }
        }   
    }//GEN-LAST:event_jb_EditarActionPerformed

    private void jtBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtBuscarMouseClicked
        // TODO add your handling code here:
        jtBuscar.setText("");
    }//GEN-LAST:event_jtBuscarMouseClicked

    private void jb_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_AgregarActionPerformed
        // TODO add your handling code here:
        
        int cantidad_inicial = 0;
        int ventas = 0;
        int compras = 0;
        
        //**********************************Comprueba si todas las casillas estan llenas***********************************//
        if(jf_Fecha.getText().equals("") ||  jcb_BodegaID.getSelectedIndex()==0||jcb_Producto.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this, "Todos los campos son requeridos!", 
                    "ERROR", JOptionPane.WARNING_MESSAGE);
        }
        else{
            int id = 0;

            //*****************comprueba si el id esta vacio ******************************//
                if(tf_inventario.getText().equals("")){
                    id = 0;
                }
                else{
                    id = Integer.parseInt((tf_inventario.getText()));
                }

            //comprobar si id existe
            if(dt_inventario.existeInventario(id)){ //Se encarga a realizar los movimientos positivos y negativos
            
            //***********************Agregar el saldo final anterior***********************//
            inv.setInventarioID(Integer.parseInt((tf_inventario.getText())));
            int numero = dt_inventario.AumentadorInventario(inv.getInventarioID());
            inv.setCant_inicial(numero);

            //*****************************Datos generales********************************//
            inv.setFecha(jf_Fecha.getText());
            inv.setProductoID(jcb_Producto.getSelectedIndex());  
            inv.setBodegaID(jcb_BodegaID.getSelectedIndex());
            
            
            
            //**************************Movimiento negativo***************************//
            if(jf_ventas.getText().equals("")){
               inv.setMovimiento_neg(0);
            }
            else{
                inv.setMovimiento_neg(Integer.parseInt((jf_ventas.getText())));
            }
                    
            //**************************Movimiento Positivo***************************//
            if(jf_compras.getText().equals("")){
                    
                inv.setMovimiento_pos(0);
            }
            else{
                inv.setMovimiento_pos(Integer.parseInt((jf_compras.getText())));
            }

            //**************************Calculo de saldo final***************************//
            cantidad_inicial = inv.getCant_inicial();
            ventas = inv.getMovimiento_neg();
            compras = inv.getMovimiento_pos();
            inv.setSaldo_final((cantidad_inicial+compras)-ventas);
            
            //*********llamar a la funcion que imprimira los datos a la tabla*************//
            dt_inventario.Movimiento(inv);
        
            }
            
            else{//se crea uno nuevo y la cantidad inicial inicia en 0
            
                //***********************Datos generales***********************//

                    inv.setCant_inicial(cantidad_inicial);
                    inv.setFecha(jf_Fecha.getText());
                    
                //**************************Combo box**************************//

                    pro = (Productos)this.jcb_Producto.getSelectedItem();
                    inv.setProductoID(pro.getProducto_id());
                    
                    b = (Bodegas)this.jcb_BodegaID.getSelectedItem();
                    inv.setBodegaID(b.getBodegaID());
                    
                      
                //**************************Movimiento Positivo***************************//
                    if(jf_ventas.getText().equals("")){
                        inv.setMovimiento_neg(0);
                    }else{
                        inv.setMovimiento_neg(Integer.parseInt((jf_ventas.getText())));

                    }
                    
                //**************************Movimiento Negativo***************************//
                    if(jf_compras.getText().equals("")){
                        inv.setMovimiento_pos(0);
                    }else{
                        inv.setMovimiento_pos(Integer.parseInt((jf_compras.getText())));
                    }
                    
                //**************************Calculo de saldo final***************************//
                    cantidad_inicial = inv.getCant_inicial();
                    ventas = inv.getMovimiento_neg();
                    compras = inv.getMovimiento_pos();
                    inv.setSaldo_final((cantidad_inicial+compras)-ventas);
                    
                //*********llamar a la funcion que imprimira los datos a la tabla*************//
                    dt_inventario.guardarInventario(inv);
                    
                }
            
            JOptionPane.showMessageDialog (this, "El inventario fue almacenado con éxito!", 
            "MENSAJE", JOptionPane.INFORMATION_MESSAGE);
            actualizarTabla();
            limpiarCampos();
    
        }
    }//GEN-LAST:event_jb_AgregarActionPerformed

    private void jtInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtInventarioMouseClicked
        // TODO add your handling code here:
        int fila = jtInventario.getSelectedRow();  
        
        //asignamos los valores a los campos del formulario
        tf_inventario.setText(jtInventario.getValueAt(fila, 0).toString());
        jcb_BodegaID.setSelectedIndex(Integer.parseInt(jtInventario.getValueAt(fila, 1).toString()));  
        jcb_Producto.setSelectedIndex(Integer.parseInt(jtInventario.getValueAt(fila, 2).toString())); 
        jf_cantInicial.setText(jtInventario.getValueAt(fila, 3).toString());
        jf_compras.setText(jtInventario.getValueAt(fila, 4).toString());
        jf_ventas.setText(jtInventario.getValueAt(fila, 5).toString());
        jf_saldoTotal.setText(jtInventario.getValueAt(fila, 6).toString());
        jf_Fecha.setText(jtInventario.getValueAt(fila, 7).toString());
        
    }//GEN-LAST:event_jtInventarioMouseClicked

    private void jtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtBuscarActionPerformed

    private void jcb_ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_ProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_ProductoActionPerformed

    private void jtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtBuscarKeyTyped
        // TODO add your handling code here:
        jtBuscar.addKeyListener(new KeyAdapter(){
            //Se ejecuta cuando el usuario libera una tecla
            @Override
            public void keyReleased(final KeyEvent e){
                String cadena = (jtBuscar.getText()).toUpperCase();
                jtBuscar.setText(cadena);
                repaint();
                filtrarTabla();
            }
        });
        trsfiltro = new TableRowSorter(jtInventario.getModel());
        jtInventario.setRowSorter(trsfiltro);
        
        
    }//GEN-LAST:event_jtBuscarKeyTyped

    private void jcb_BodegaIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_BodegaIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_BodegaIDActionPerformed

    private void jcb_BodegaIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcb_BodegaIDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_BodegaIDMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInventarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInventarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInventarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInventarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInventarios().setVisible(true);
            }
        });
    }
        
        private void llenarTablaProductos()
    {
         //llenamos la lista
        listInventario = dt_inventario.listarInventario();
        
        //creamos un arraylist con las columnas del modelo
        ArrayList<Object> listNombreColumnas = new ArrayList<Object>();
        listNombreColumnas.add("InventarioID");
        listNombreColumnas.add("BodegaID");
        listNombreColumnas.add("ProductoID");
        listNombreColumnas.add("Cant_inicial");
        listNombreColumnas.add("Movimiento_pos");
        listNombreColumnas.add("Movimiento_neg");
        listNombreColumnas.add("Saldo_final");
        listNombreColumnas.add("Fecha");

        
        //recorremos cada elemento del arraylist y creamos un objeto
        for(Object column : listNombreColumnas){
            //asignamos las columnas al modelo
            myData.addColumn(column);
        }
        
       //recorremos cada elemento de la lista y creamos el objeto
        for(Inventarios inv: listInventario){
            Object[] datosInv = new Object[]{inv.getInventarioID(), inv.getBodegaID(),inv.getProductoID(),inv.getCant_inicial(), inv.getMovimiento_pos(), inv.getMovimiento_neg(),inv.getSaldo_final(), inv.getFecha()};
            //asignamos un arreglo de objetos a una fila del modelo
            myData.addRow(datosInv);
        }
        //Asignamos el modelo y/o coleccion de datos a la tabla
        jtInventario.setModel(myData);
    }
        
        private void llenarComboBodega(){
        //llenamos la lista
        listBodega = dt_bodega.listarBodegas();
        
        //recorremos cada elemento de la lista y creamos el objeto
        for(Bodegas bod: listBodega){
            //asignamos el objeto creado al combobox
            this.jcb_BodegaID.addItem(bod);   
        }
          
    }
        
        private void llenarComboProducto(){
        //llenamos la lista
        listProductos = dt_producto.listarProductos();
        
        //recorremos cada elemento de la lista y creamos el objeto
        for(Productos pro: listProductos){
            //asignamos el objeto creado al combobox
            this.jcb_Producto.addItem(pro);   
        }
          
    }
        private void limpiarCampos(){
        this.jf_Fecha.setText("");
        this.jf_ventas.setText("");
        this.jf_compras.setText("");
        this.jf_cantInicial.setText("");
        this.tf_inventario.setText("");
        this.jf_saldoTotal.setText("");
        this.jcb_BodegaID.setSelectedIndex(0);
        this.jcb_Producto.setSelectedIndex(0);
    }
        
     private void filtrarTabla(){
       trsfiltro.setRowFilter(RowFilter.regexFilter(jtBuscar.getText(),0));
    }
        
        private void actualizarTabla(){
        myData.setColumnCount(0);
        myData.setRowCount(0);
        llenarTablaProductos();
    }
        
        

    public JPanel getFondo(){
        return jPanel1;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_Agregar;
    private javax.swing.JButton jb_Editar;
    private javax.swing.JButton jb_Eliminar;
    private javax.swing.JButton jb_Guardar;
    private javax.swing.JComboBox<Object> jcb_BodegaID;
    private javax.swing.JComboBox<Object> jcb_Producto;
    private javax.swing.JTextField jf_Fecha;
    private javax.swing.JTextField jf_cantInicial;
    private javax.swing.JTextField jf_compras;
    private javax.swing.JTextField jf_saldoTotal;
    private javax.swing.JTextField jf_ventas;
    private javax.swing.JTextField jtBuscar;
    private javax.swing.JTable jtInventario;
    private javax.swing.JTextField tf_inventario;
    // End of variables declaration//GEN-END:variables
}
